/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ambaltextiles;

import ambaltextiles.databaseWorks.DatabaseFunctions;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sridhar
 */
public class AddCustomer extends javax.swing.JFrame {

    DatabaseFunctions df;
    DefaultTableModel dm;
    DefaultTableCellRenderer centerRenderer;
    JScrollPane sp;

    String[] head;
    private String custid, n, a1, a2, a3, t, sc, pho;

    /**
     * Creates new form Customers
     */
    public AddCustomer() {

        dm = new DefaultTableModel(0, 0);

        initComponents();

        head = new String[]{"ADDRESS DETAILS"}; // declare header fields
        dm.setColumnIdentifiers(head);

        // formatting data in cells as center
        centerRenderer = new DefaultTableCellRenderer(); // instance of the DefaultTableCellRenderer
        // applying the above format to all cells in table
        customerListTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);

    }

    public String getN() {
        return n;
    }

    public void setN(String n) {
        this.n = n;
    }

    public String getA1() {
        return a1;
    }

    public void setA1(String a1) {
        this.a1 = a1;
    }

    public String getA2() {
        return a2;
    }

    public void setA2(String a2) {
        this.a2 = a2;
    }

    public String getA3() {
        return a3;
    }

    public void setA3(String a3) {
        this.a3 = a3;
    }

    public String getT() {
        return t;
    }

    public void setT(String t) {
        this.t = t;
    }

    public String getSc() {
        return sc;
    }

    public void setSc(String sc) {
        this.sc = sc;
    }

    public String getPho() {
        return pho;
    }

    public void setPho(String pho) {
        this.pho = pho;
    }

    public String getCustid() {
        return custid;
    }

    public void setCustid(String custid) {
        this.custid = custid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameOfCompany = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addressLine1 = new javax.swing.JTextField();
        addressLine2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressLine3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gstinNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stateCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        addAccount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerListTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        customerId = new javax.swing.JTextField();
        updateAccount = new javax.swing.JButton();
        clearDetails = new javax.swing.JButton();
        viewList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(47, 93, 129));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.setForeground(new java.awt.Color(47, 93, 129));

        jLabel1.setFont(new java.awt.Font("Supercell-Magic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW CUSTOMER");

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ambaltextiles/images/close.png"))); // NOI18N
        close.setToolTipText("Close");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME OF THE COMPANY/ CUSTOMER");

        nameOfCompany.setToolTipText("Customer Name / Company Name");

        jLabel3.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS LINE I");

        addressLine1.setToolTipText("Address Line 1");

        addressLine2.setToolTipText("Address Line 2");

        jLabel4.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADDRESS LINE II");

        addressLine3.setToolTipText("Address Line 3");

        jLabel5.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS LINE III");

        jLabel6.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GSTIN NUMBER");

        gstinNumber.setToolTipText("TIN Number");

        jLabel7.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STATE CODE");

        stateCode.setToolTipText("State Code");

        jLabel8.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE NUMBER");

        phoneNumber.setToolTipText("phone Number");

        addAccount.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        addAccount.setText("ADD");
        addAccount.setToolTipText("Add Account ");
        addAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountActionPerformed(evt);
            }
        });

        customerListTable.setFont(new java.awt.Font("Consolas", 1, 13)); // NOI18N
        customerListTable.setModel(dm);
        customerListTable.setToolTipText("Customer Details Table");
        customerListTable.setRowHeight(25);
        jScrollPane1.setViewportView(customerListTable);

        jLabel9.setFont(new java.awt.Font("Supercell-Magic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CUSTOMER LIST");

        jLabel10.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CUSTOMER ID");

        customerId.setToolTipText("Customer Id");

        updateAccount.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        updateAccount.setText("UPDATE");
        updateAccount.setToolTipText("Update Customer Account");
        updateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccountActionPerformed(evt);
            }
        });

        clearDetails.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        clearDetails.setText("CLEAR");
        clearDetails.setToolTipText("Clear Details");
        clearDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearDetailsActionPerformed(evt);
            }
        });

        viewList.setFont(new java.awt.Font("Supercell-Magic", 0, 12)); // NOI18N
        viewList.setText("view list");
        viewList.setToolTipText("View List of Cutomer Accounts");
        viewList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nameOfCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(addressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(addressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(gstinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(stateCode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(addAccount)
                        .addGap(51, 51, 51)
                        .addComponent(clearDetails)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateAccount)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9)
                                .addGap(73, 73, 73)
                                .addComponent(viewList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(close))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)
                        .addComponent(viewList)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameOfCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gstinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAccount)
                            .addComponent(clearDetails))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(customerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateAccount))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1100, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        if (isDisplayable()) {
            int flag = JOptionPane.showConfirmDialog(this, "Do you want to close the window ?");
            if (flag == JOptionPane.YES_OPTION) {
                dispose(); // To close this frame
                Home homeWindow;
                try {
                    homeWindow = new Home();
                    homeWindow.setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    // don't do anything
                }
            }
        }
    }//GEN-LAST:event_closeMouseClicked

    private void addAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountActionPerformed
        df = new DatabaseFunctions();
        try {
            if (!nameOfCompany.getText().equals("") && !addressLine1.getText().equals("") && !addressLine2.getText().equals("")
                    && !gstinNumber.getText().equals("") && !stateCode.getText().equals("") && !phoneNumber.getText().equals("") && phoneNumber.getText().length() < 12 && phoneNumber.getText().length() > 5) {
                df.insertionAccount(nameOfCompany.getText(), addressLine1.getText(), addressLine2.getText(),
                        addressLine3.getText(), gstinNumber.getText(), stateCode.getText(), phoneNumber.getText());
                tableDatas();
            } else if (!nameOfCompany.getText().equals("") && !addressLine1.getText().equals("") && !addressLine2.getText().equals("")
                    && !addressLine3.getText().equals("") && !gstinNumber.getText().equals("") && !stateCode.getText().equals("") && !phoneNumber.getText().equals("")
                     && (phoneNumber.getText().length() >= 12 || phoneNumber.getText().length() <= 5)) {
                JOptionPane.showMessageDialog(this, "You must enter valid phone number", "Number Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "You must enter all fields \n(optional field: Address Line3)", "Empty Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            // don't do anything
        }
    }//GEN-LAST:event_addAccountActionPerformed

    private void updateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccountActionPerformed
        // TODO add your handling code here:
        df = new DatabaseFunctions();
        try {
            if (nameOfCompany.getText().equals("") && addressLine1.getText().equals("") && addressLine2.getText().equals("")
                    && addressLine3.getText().equals("") && gstinNumber.getText().equals("") && stateCode.getText().equals("") && phoneNumber.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "You must enter anyone of the fields to update", "Empty Error", JOptionPane.ERROR_MESSAGE);
            } else if (!phoneNumber.getText().equals("") && (phoneNumber.getText().length() >= 12 || phoneNumber.getText().length() <= 5)) {
                JOptionPane.showMessageDialog(this, "You must enter valid phone number", "Number Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (!customerId.getText().equals("")) {
                    df.updateAccount(Integer.parseInt(customerId.getText()), nameOfCompany.getText(), addressLine1.getText(), addressLine2.getText(),
                            addressLine3.getText(), gstinNumber.getText(), stateCode.getText(), phoneNumber.getText());
                    clearAll();
                    customerId.setText("");
                    tableDatas();
                } else {
                    JOptionPane.showMessageDialog(this, "You must enter Customer Id field", "Empty Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            // don't do anything
        }
    }//GEN-LAST:event_updateAccountActionPerformed

    private void clearDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearDetailsActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_clearDetailsActionPerformed

    private void viewListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListActionPerformed
        // TODO add your handling code here:
        tableDatas();
    }//GEN-LAST:event_viewListActionPerformed

    private void clearAll() {
        nameOfCompany.setText("");
        addressLine1.setText("");
        addressLine2.setText("");
        addressLine3.setText("");
        gstinNumber.setText("");
        stateCode.setText("");
        phoneNumber.setText("");
    }

    private void tableDatas() {
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }

        try {
            df = new DatabaseFunctions();
            ArrayList<AddCustomer> l = df.findAll();
            l.forEach((list) -> {
                dm.addRow(new Object[]{
                    list.getCustid() + " -> "
                    + list.getN() + ", "
                    + list.getA1() + ", "
                    + list.getA2() + ", "
                    + list.getA3() + ", "
                    + list.getT() + ", "
                    + list.getSc() + ", "
                    + list.getPho()
                });
            });
        } catch (SQLException | ClassNotFoundException ex) {
            // don't do anything
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccount;
    private javax.swing.JTextField addressLine1;
    private javax.swing.JTextField addressLine2;
    private javax.swing.JTextField addressLine3;
    private javax.swing.JButton clearDetails;
    private javax.swing.JLabel close;
    private javax.swing.JTextField customerId;
    private javax.swing.JTable customerListTable;
    private javax.swing.JTextField gstinNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameOfCompany;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField stateCode;
    private javax.swing.JButton updateAccount;
    private javax.swing.JButton viewList;
    // End of variables declaration//GEN-END:variables

}
